global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Application metrics
  - job_name: 'ctp-app'
    static_configs:
      - targets: ['ctp-app:3002']
    metrics_path: '/metrics'

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Neo4j metrics
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: '/metrics'